/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exchange_r;

import javax.swing.JOptionPane;

/**
 *
 * @author aaaa
 */
public class Admin_Dasboard extends javax.swing.JFrame {

    public Admin_Dasboard() {
        initComponents();
        // center form in the screen 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_Users = new javax.swing.JButton();
        jButton1_Users1 = new javax.swing.JButton();
        jButton1_Users3 = new javax.swing.JButton();
        jButton1_Users4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1_Users2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exchange_r/uicon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jButton1_Users.setBackground(new java.awt.Color(204, 153, 255));
        jButton1_Users.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1_Users.setText("Home");
        jButton1_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_UsersMouseClicked(evt);
            }
        });
        jButton1_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_UsersActionPerformed(evt);
            }
        });

        jButton1_Users1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1_Users1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1_Users1.setText("Delete User");
        jButton1_Users1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_Users1MouseClicked(evt);
            }
        });

        jButton1_Users3.setBackground(new java.awt.Color(204, 153, 255));
        jButton1_Users3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1_Users3.setText("LogOut");
        jButton1_Users3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Users3ActionPerformed(evt);
            }
        });

        jButton1_Users4.setBackground(new java.awt.Color(204, 153, 255));
        jButton1_Users4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1_Users4.setText("All Users");
        jButton1_Users4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_Users4MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exchange_r/uicon.png"))); // NOI18N
        jLabel3.setText("jLabel2");

        jButton1_Users2.setBackground(new java.awt.Color(204, 153, 255));
        jButton1_Users2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1_Users2.setText("Profile");
        jButton1_Users2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_Users2MouseClicked(evt);
            }
        });
        jButton1_Users2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Users2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1_Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_Users4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_Users1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_Users3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1_Users2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1_Users, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1_Users4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1_Users1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1_Users2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1_Users3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_UsersActionPerformed

    }//GEN-LAST:event_jButton1_UsersActionPerformed

    private void jButton1_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_UsersMouseClicked
        admin_home_page obj1 = new admin_home_page();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj1).setVisible(true);
    }//GEN-LAST:event_jButton1_UsersMouseClicked

    private void jButton1_Users4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_Users4MouseClicked
        admin_all_users obj = new admin_all_users();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_jButton1_Users4MouseClicked

    private void jButton1_Users1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_Users1MouseClicked
        admin_delete_user obj = new admin_delete_user();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_jButton1_Users1MouseClicked

    private void jButton1_Users2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_Users2MouseClicked
        admin_profile_page obj = new admin_profile_page();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_jButton1_Users2MouseClicked

    private void jButton1_Users2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Users2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_Users2ActionPerformed

    private void jButton1_Users3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Users3ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you Sure", "", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            this.dispose();
            Home_Page obj = new Home_Page();
            obj.setVisible(true);
            Login_Form_1.admin_email = null;
        }
    }//GEN-LAST:event_jButton1_Users3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Users;
    private javax.swing.JButton jButton1_Users1;
    private javax.swing.JButton jButton1_Users2;
    private javax.swing.JButton jButton1_Users3;
    private javax.swing.JButton jButton1_Users4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
